[package]
name = "ansiktemuskler4489/guistruct"
version = "0.1.0"
license = "MIT"
author = "ansiktemuskler4489"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/ansiktemuskler4489/GuiStruct"

[dependencies]
